import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/providers";
import { getDirection } from "@core/i18n/utils";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}): JSX.Element {
  const messages = useMessages();
  
  return (
    <html lang={locale} dir={getDirection(locale)}>
      <body className={inter.className}>
        <NextIntlClientProvider
          messages={{
            "Core": messages["Core"] || {},
          }}
        >
          <Providers locale={locale}>
            {children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

